name: Rotate Secrets

on:
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Rotate AWS Secrets
        run: terraform apply -target=module.aws_secrets -auto-approve

      - name: Rotate Azure Secrets
        run: terraform apply -target=module.azure_secrets -auto-approve

      - name: Rotate GCP Secrets
        run: terraform apply -target=module.gcp_secrets -auto-approve

      - name: Log Rotation Event
        run: echo "$(date) - Secrets rotated successfully" >> logs/rotation.log
